### ISSUE TITLE
Whats the entry point?

### ISSUE THREAD

**Issue by lostinblue** [siongui/godom#1]
Its very difficult in comparison to the other dom libraries to see where the entry point is. There is no example where you load HTML from a string or initialize a Document object. Can you provide an example?

**Comment by siongui** [comment]
If you have some experience with JavaScript, see [Synonyms - Go and JavaScript](https://siongui.github.io/2017/12/07/synonyms-go-and-javascript/).
Otherwise you can see [Frontend Programming in Go](https://siongui.github.io/2017/12/04/frontend-programming-in-go/).

**Comment by siongui** [comment]
I add this in README. If this is not what you want, you can re-open this issue and give more details.
